server:
  port: 9091
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456789
    url: jdbc:mysql://usermanagement-db.cdszvx4u4dxh.ap-south-1.rds.amazonaws.com:3306/usermanagement
    username: admin
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: vinodsinghrawat1905@gmail.com
    password: txylcipjskpubwfy
    properties:
      mail:
       smtp:
        starttls:
         enable: true
       auth: true
app:
 messages:
  invalidCredentials: Credentials are Invalid
  accountLocked: Your account is locked
  regSuccess: Registration almost completed. Please check your email to proceed.
  unlockSucc: Your account unlocked successfully
  regEmailSub: User Registration Successfull | Ashok IT
  forgPtPwdEmailSub: Forgot Password | Ashok IT
  forgotPwdSucc: Email sent with password
  forgotPwdFail: Enter Correct Email id
  regMailBodyFile: UNLOCK-ACC-EMAIL-BODY-TEMPLATE.txt
  forgotPwdMailBodyFile: RECOVER-PASSWORD-EMAIL-BODY-TEMPLATE.txt
